// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq が本サンドボックス環境ではネットワーク/ツールチェーンの
// 問題で実行できなかったため、moqが生成する形(XxxFunc + 呼び出し履歴の記録)に
// 合わせて手書きしている。go:generateが実行可能な環境になり次第、
// `go generate ./internal/domain/user/...` で本物の生成物に置き換えること。

package moq

import (
	"context"
	"sync"

	"github.com/o-ga09/go-backend-template/internal/domain/user"
)

// IUserRepositoryMock はuser.IUserRepositoryのテスト用モック。
type IUserRepositoryMock struct {
	FindByIDFunc        func(ctx context.Context, id string) (*user.User, error)
	FindByGoogleSubFunc func(ctx context.Context, googleSub string) (*user.User, error)
	CreateFunc          func(ctx context.Context, u *user.User) error
	UpdateFunc          func(ctx context.Context, u *user.User) error

	calls struct {
		FindByID []struct {
			Ctx context.Context
			ID  string
		}
		FindByGoogleSub []struct {
			Ctx       context.Context
			GoogleSub string
		}
		Create []struct {
			Ctx context.Context
			U   *user.User
		}
		Update []struct {
			Ctx context.Context
			U   *user.User
		}
	}
	lockFindByID        sync.RWMutex
	lockFindByGoogleSub sync.RWMutex
	lockCreate          sync.RWMutex
	lockUpdate          sync.RWMutex
}

var _ user.IUserRepository = (*IUserRepositoryMock)(nil)

// FindByID はFindByIDFuncを呼び出し、呼び出し履歴を記録する。
func (m *IUserRepositoryMock) FindByID(ctx context.Context, id string) (*user.User, error) {
	m.lockFindByID.Lock()
	m.calls.FindByID = append(m.calls.FindByID, struct {
		Ctx context.Context
		ID  string
	}{ctx, id})
	m.lockFindByID.Unlock()
	return m.FindByIDFunc(ctx, id)
}

// FindByGoogleSub はFindByGoogleSubFuncを呼び出し、呼び出し履歴を記録する。
func (m *IUserRepositoryMock) FindByGoogleSub(ctx context.Context, googleSub string) (*user.User, error) {
	m.lockFindByGoogleSub.Lock()
	m.calls.FindByGoogleSub = append(m.calls.FindByGoogleSub, struct {
		Ctx       context.Context
		GoogleSub string
	}{ctx, googleSub})
	m.lockFindByGoogleSub.Unlock()
	return m.FindByGoogleSubFunc(ctx, googleSub)
}

// Create はCreateFuncを呼び出し、呼び出し履歴を記録する。
func (m *IUserRepositoryMock) Create(ctx context.Context, u *user.User) error {
	m.lockCreate.Lock()
	m.calls.Create = append(m.calls.Create, struct {
		Ctx context.Context
		U   *user.User
	}{ctx, u})
	m.lockCreate.Unlock()
	return m.CreateFunc(ctx, u)
}

// Update はUpdateFuncを呼び出し、呼び出し履歴を記録する。
func (m *IUserRepositoryMock) Update(ctx context.Context, u *user.User) error {
	m.lockUpdate.Lock()
	m.calls.Update = append(m.calls.Update, struct {
		Ctx context.Context
		U   *user.User
	}{ctx, u})
	m.lockUpdate.Unlock()
	return m.UpdateFunc(ctx, u)
}

// FindByIDCalls はFindByIDの呼び出し履歴を返す。
func (m *IUserRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	m.lockFindByID.RLock()
	defer m.lockFindByID.RUnlock()
	return m.calls.FindByID
}

// FindByGoogleSubCalls はFindByGoogleSubの呼び出し履歴を返す。
func (m *IUserRepositoryMock) FindByGoogleSubCalls() []struct {
	Ctx       context.Context
	GoogleSub string
} {
	m.lockFindByGoogleSub.RLock()
	defer m.lockFindByGoogleSub.RUnlock()
	return m.calls.FindByGoogleSub
}

// CreateCalls はCreateの呼び出し履歴を返す。
func (m *IUserRepositoryMock) CreateCalls() []struct {
	Ctx context.Context
	U   *user.User
} {
	m.lockCreate.RLock()
	defer m.lockCreate.RUnlock()
	return m.calls.Create
}

// UpdateCalls はUpdateの呼び出し履歴を返す。
func (m *IUserRepositoryMock) UpdateCalls() []struct {
	Ctx context.Context
	U   *user.User
} {
	m.lockUpdate.RLock()
	defer m.lockUpdate.RUnlock()
	return m.calls.Update
}
