version: "2"

linters:
  default: none
  enable:
    - unused
    - errcheck
    # - gocognit
    # - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace
  settings:
    gocyclo:
      min-complexity: 30
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports