coverage:
  paths:
    - backend/coverage.out
codeToTestRatio:
  code:
    - "backend/**/*.go"
    - "!backend/**/*_test.go"
  test:
    - "backend/**/*_test.go"
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}