version: "3.9"
services:
  app:
    build:
      context: ../
      dockerfile: docker/go/Dockerfile
      target: dev
    environment:
      ENV: DEV
      PORT: 8081
      GOOGLEAI_API_KEY: $GOOGLEAI_API_KEY
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
