// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq が本サンドボックス環境ではネットワーク/ツールチェーンの
// 問題で実行できなかったため、moqが生成する形(XxxFunc + 呼び出し履歴の記録)に
// 合わせて手書きしている。go:generateが実行可能な環境になり次第、
// `go generate ./internal/domain/order/...` で本物の生成物に置き換えること。

package moq

import (
	"context"
	"sync"

	"github.com/o-ga09/go-backend-template/internal/domain/order"
)

// IOrderRepositoryMock はorder.IOrderRepositoryのテスト用モック。
type IOrderRepositoryMock struct {
	CreateFunc       func(ctx context.Context, o *order.Order) error
	FindByIDFunc     func(ctx context.Context, id string) (*order.Order, error)
	ListByUserIDFunc func(ctx context.Context, userID string) ([]*order.Order, error)

	calls struct {
		Create []struct {
			Ctx context.Context
			O   *order.Order
		}
		FindByID []struct {
			Ctx context.Context
			ID  string
		}
		ListByUserID []struct {
			Ctx    context.Context
			UserID string
		}
	}
	lockCreate       sync.RWMutex
	lockFindByID     sync.RWMutex
	lockListByUserID sync.RWMutex
}

var _ order.IOrderRepository = (*IOrderRepositoryMock)(nil)

// Create はCreateFuncを呼び出し、呼び出し履歴を記録する。
func (m *IOrderRepositoryMock) Create(ctx context.Context, o *order.Order) error {
	m.lockCreate.Lock()
	m.calls.Create = append(m.calls.Create, struct {
		Ctx context.Context
		O   *order.Order
	}{ctx, o})
	m.lockCreate.Unlock()
	return m.CreateFunc(ctx, o)
}

// FindByID はFindByIDFuncを呼び出し、呼び出し履歴を記録する。
func (m *IOrderRepositoryMock) FindByID(ctx context.Context, id string) (*order.Order, error) {
	m.lockFindByID.Lock()
	m.calls.FindByID = append(m.calls.FindByID, struct {
		Ctx context.Context
		ID  string
	}{ctx, id})
	m.lockFindByID.Unlock()
	return m.FindByIDFunc(ctx, id)
}

// ListByUserID はListByUserIDFuncを呼び出し、呼び出し履歴を記録する。
func (m *IOrderRepositoryMock) ListByUserID(ctx context.Context, userID string) ([]*order.Order, error) {
	m.lockListByUserID.Lock()
	m.calls.ListByUserID = append(m.calls.ListByUserID, struct {
		Ctx    context.Context
		UserID string
	}{ctx, userID})
	m.lockListByUserID.Unlock()
	return m.ListByUserIDFunc(ctx, userID)
}

// CreateCalls はCreateの呼び出し履歴を返す。
func (m *IOrderRepositoryMock) CreateCalls() []struct {
	Ctx context.Context
	O   *order.Order
} {
	m.lockCreate.RLock()
	defer m.lockCreate.RUnlock()
	return m.calls.Create
}

// FindByIDCalls はFindByIDの呼び出し履歴を返す。
func (m *IOrderRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	m.lockFindByID.RLock()
	defer m.lockFindByID.RUnlock()
	return m.calls.FindByID
}

// ListByUserIDCalls はListByUserIDの呼び出し履歴を返す。
func (m *IOrderRepositoryMock) ListByUserIDCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	m.lockListByUserID.RLock()
	defer m.lockListByUserID.RUnlock()
	return m.calls.ListByUserID
}
