// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq が本サンドボックス環境ではネットワーク/ツールチェーンの
// 問題で実行できなかったため、moqが生成する形(XxxFunc + 呼び出し履歴の記録)に
// 合わせて手書きしている。go:generateが実行可能な環境になり次第、
// `go generate ./internal/domain/cart/...` で本物の生成物に置き換えること。

package moq

import (
	"context"
	"sync"

	"github.com/o-ga09/go-backend-template/internal/domain/cart"
)

// ICartRepositoryMock はcart.ICartRepositoryのテスト用モック。
type ICartRepositoryMock struct {
	FindByUserIDFunc       func(ctx context.Context, userID string) (*cart.Cart, error)
	CreateFunc             func(ctx context.Context, userID string) (*cart.Cart, error)
	AddItemFunc            func(ctx context.Context, cartID, productID string, quantity int) error
	UpdateItemQuantityFunc func(ctx context.Context, cartID, productID string, quantity int) error
	RemoveItemFunc         func(ctx context.Context, cartID, productID string) error
	ClearFunc              func(ctx context.Context, cartID string) error

	calls struct {
		FindByUserID []struct {
			Ctx    context.Context
			UserID string
		}
		Create []struct {
			Ctx    context.Context
			UserID string
		}
		AddItem []struct {
			Ctx       context.Context
			CartID    string
			ProductID string
			Quantity  int
		}
		UpdateItemQuantity []struct {
			Ctx       context.Context
			CartID    string
			ProductID string
			Quantity  int
		}
		RemoveItem []struct {
			Ctx       context.Context
			CartID    string
			ProductID string
		}
		Clear []struct {
			Ctx    context.Context
			CartID string
		}
	}
	lockFindByUserID       sync.RWMutex
	lockCreate             sync.RWMutex
	lockAddItem            sync.RWMutex
	lockUpdateItemQuantity sync.RWMutex
	lockRemoveItem         sync.RWMutex
	lockClear              sync.RWMutex
}

var _ cart.ICartRepository = (*ICartRepositoryMock)(nil)

// FindByUserID はFindByUserIDFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) FindByUserID(ctx context.Context, userID string) (*cart.Cart, error) {
	m.lockFindByUserID.Lock()
	m.calls.FindByUserID = append(m.calls.FindByUserID, struct {
		Ctx    context.Context
		UserID string
	}{ctx, userID})
	m.lockFindByUserID.Unlock()
	return m.FindByUserIDFunc(ctx, userID)
}

// Create はCreateFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) Create(ctx context.Context, userID string) (*cart.Cart, error) {
	m.lockCreate.Lock()
	m.calls.Create = append(m.calls.Create, struct {
		Ctx    context.Context
		UserID string
	}{ctx, userID})
	m.lockCreate.Unlock()
	return m.CreateFunc(ctx, userID)
}

// AddItem はAddItemFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) AddItem(ctx context.Context, cartID, productID string, quantity int) error {
	m.lockAddItem.Lock()
	m.calls.AddItem = append(m.calls.AddItem, struct {
		Ctx       context.Context
		CartID    string
		ProductID string
		Quantity  int
	}{ctx, cartID, productID, quantity})
	m.lockAddItem.Unlock()
	return m.AddItemFunc(ctx, cartID, productID, quantity)
}

// UpdateItemQuantity はUpdateItemQuantityFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) UpdateItemQuantity(ctx context.Context, cartID, productID string, quantity int) error {
	m.lockUpdateItemQuantity.Lock()
	m.calls.UpdateItemQuantity = append(m.calls.UpdateItemQuantity, struct {
		Ctx       context.Context
		CartID    string
		ProductID string
		Quantity  int
	}{ctx, cartID, productID, quantity})
	m.lockUpdateItemQuantity.Unlock()
	return m.UpdateItemQuantityFunc(ctx, cartID, productID, quantity)
}

// RemoveItem はRemoveItemFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) RemoveItem(ctx context.Context, cartID, productID string) error {
	m.lockRemoveItem.Lock()
	m.calls.RemoveItem = append(m.calls.RemoveItem, struct {
		Ctx       context.Context
		CartID    string
		ProductID string
	}{ctx, cartID, productID})
	m.lockRemoveItem.Unlock()
	return m.RemoveItemFunc(ctx, cartID, productID)
}

// Clear はClearFuncを呼び出し、呼び出し履歴を記録する。
func (m *ICartRepositoryMock) Clear(ctx context.Context, cartID string) error {
	m.lockClear.Lock()
	m.calls.Clear = append(m.calls.Clear, struct {
		Ctx    context.Context
		CartID string
	}{ctx, cartID})
	m.lockClear.Unlock()
	return m.ClearFunc(ctx, cartID)
}

// FindByUserIDCalls はFindByUserIDの呼び出し履歴を返す。
func (m *ICartRepositoryMock) FindByUserIDCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	m.lockFindByUserID.RLock()
	defer m.lockFindByUserID.RUnlock()
	return m.calls.FindByUserID
}

// CreateCalls はCreateの呼び出し履歴を返す。
func (m *ICartRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	m.lockCreate.RLock()
	defer m.lockCreate.RUnlock()
	return m.calls.Create
}

// AddItemCalls はAddItemの呼び出し履歴を返す。
func (m *ICartRepositoryMock) AddItemCalls() []struct {
	Ctx       context.Context
	CartID    string
	ProductID string
	Quantity  int
} {
	m.lockAddItem.RLock()
	defer m.lockAddItem.RUnlock()
	return m.calls.AddItem
}

// UpdateItemQuantityCalls はUpdateItemQuantityの呼び出し履歴を返す。
func (m *ICartRepositoryMock) UpdateItemQuantityCalls() []struct {
	Ctx       context.Context
	CartID    string
	ProductID string
	Quantity  int
} {
	m.lockUpdateItemQuantity.RLock()
	defer m.lockUpdateItemQuantity.RUnlock()
	return m.calls.UpdateItemQuantity
}

// RemoveItemCalls はRemoveItemの呼び出し履歴を返す。
func (m *ICartRepositoryMock) RemoveItemCalls() []struct {
	Ctx       context.Context
	CartID    string
	ProductID string
} {
	m.lockRemoveItem.RLock()
	defer m.lockRemoveItem.RUnlock()
	return m.calls.RemoveItem
}

// ClearCalls はClearの呼び出し履歴を返す。
func (m *ICartRepositoryMock) ClearCalls() []struct {
	Ctx    context.Context
	CartID string
} {
	m.lockClear.RLock()
	defer m.lockClear.RUnlock()
	return m.calls.Clear
}
