// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq が本サンドボックス環境ではネットワーク/ツールチェーンの
// 問題で実行できなかったため、moqが生成する形(XxxFunc + 呼び出し履歴の記録)に
// 合わせて手書きしている。go:generateが実行可能な環境になり次第、
// `go generate ./internal/domain/product/...` で本物の生成物に置き換えること。

package moq

import (
	"context"
	"sync"

	"github.com/o-ga09/go-backend-template/internal/domain/product"
)

// IProductRepositoryMock はproduct.IProductRepositoryのテスト用モック。
type IProductRepositoryMock struct {
	FindByIDFunc      func(ctx context.Context, id string) (*product.Product, error)
	ListFunc          func(ctx context.Context) ([]*product.Product, error)
	DecreaseStockFunc func(ctx context.Context, productID string, quantity int) error

	calls struct {
		FindByID []struct {
			Ctx context.Context
			ID  string
		}
		List []struct {
			Ctx context.Context
		}
		DecreaseStock []struct {
			Ctx       context.Context
			ProductID string
			Quantity  int
		}
	}
	lockFindByID      sync.RWMutex
	lockList          sync.RWMutex
	lockDecreaseStock sync.RWMutex
}

var _ product.IProductRepository = (*IProductRepositoryMock)(nil)

// FindByID はFindByIDFuncを呼び出し、呼び出し履歴を記録する。
func (m *IProductRepositoryMock) FindByID(ctx context.Context, id string) (*product.Product, error) {
	m.lockFindByID.Lock()
	m.calls.FindByID = append(m.calls.FindByID, struct {
		Ctx context.Context
		ID  string
	}{ctx, id})
	m.lockFindByID.Unlock()
	return m.FindByIDFunc(ctx, id)
}

// List はListFuncを呼び出し、呼び出し履歴を記録する。
func (m *IProductRepositoryMock) List(ctx context.Context) ([]*product.Product, error) {
	m.lockList.Lock()
	m.calls.List = append(m.calls.List, struct {
		Ctx context.Context
	}{ctx})
	m.lockList.Unlock()
	return m.ListFunc(ctx)
}

// DecreaseStock はDecreaseStockFuncを呼び出し、呼び出し履歴を記録する。
func (m *IProductRepositoryMock) DecreaseStock(ctx context.Context, productID string, quantity int) error {
	m.lockDecreaseStock.Lock()
	m.calls.DecreaseStock = append(m.calls.DecreaseStock, struct {
		Ctx       context.Context
		ProductID string
		Quantity  int
	}{ctx, productID, quantity})
	m.lockDecreaseStock.Unlock()
	return m.DecreaseStockFunc(ctx, productID, quantity)
}

// FindByIDCalls はFindByIDの呼び出し履歴を返す。
func (m *IProductRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	m.lockFindByID.RLock()
	defer m.lockFindByID.RUnlock()
	return m.calls.FindByID
}

// ListCalls はListの呼び出し履歴を返す。
func (m *IProductRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	m.lockList.RLock()
	defer m.lockList.RUnlock()
	return m.calls.List
}

// DecreaseStockCalls はDecreaseStockの呼び出し履歴を返す。
func (m *IProductRepositoryMock) DecreaseStockCalls() []struct {
	Ctx       context.Context
	ProductID string
	Quantity  int
} {
	m.lockDecreaseStock.RLock()
	defer m.lockDecreaseStock.RUnlock()
	return m.calls.DecreaseStock
}
