// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq が本サンドボックス環境ではgo/packagesの内部エラー
// ("internal error: package \"context\" without types was imported from ...")
// により実行できなかったため、moqが生成する形(XxxFunc + 呼び出し履歴の記録)に
// 合わせて手書きしている(internal/domain/user/mock/user_repository_mock.goと同じ
// パターン)。go:generateが実行可能な環境になり次第、
// `go generate ./internal/database/...` で本物の生成物に置き換えること。

package mock

import (
	"context"
	"sync"

	"github.com/o-ga09/go-backend-template/internal/database"
)

// ITransactionManagerMock はdatabase.ITransactionManagerのテスト用モック。
type ITransactionManagerMock struct {
	RunInTxFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	calls struct {
		RunInTx []struct {
			Ctx context.Context
			Fn  func(ctx context.Context) error
		}
	}
	lockRunInTx sync.RWMutex
}

var _ database.ITransactionManager = (*ITransactionManagerMock)(nil)

// RunInTx はRunInTxFuncを呼び出し、呼び出し履歴を記録する。
func (m *ITransactionManagerMock) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	if m.RunInTxFunc == nil {
		panic("ITransactionManagerMock.RunInTxFunc: method is nil but ITransactionManager.RunInTx was just called")
	}
	m.lockRunInTx.Lock()
	m.calls.RunInTx = append(m.calls.RunInTx, struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{ctx, fn})
	m.lockRunInTx.Unlock()
	return m.RunInTxFunc(ctx, fn)
}

// RunInTxCalls はRunInTxの呼び出し履歴を返す。
func (m *ITransactionManagerMock) RunInTxCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	m.lockRunInTx.RLock()
	defer m.lockRunInTx.RUnlock()
	return m.calls.RunInTx
}
